config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :dogs do
    member do
      get "like"
    end
  end
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many_attached :images
  belongs_to :user

  alias_method :owner, :user

  validates :name, presence: true
  validates :owner, presence: true
  validates :description, presence: true
  validates :images, presence: true

  acts_as_votable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_login
    redirect_to dogs_url unless current_user
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :description, :images)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :set_likes, only: %i[destroy]

  def new
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @like.user_id = current_user.id
    @dog = Dog.find(params[:dog_id])

    respond_to do |format|
      if @like.save
        format.html { redirect_to @dog, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update; end

  def destroy; end

  private

  def set_likes
    @like = Like.find(params[:id])
    @dog = Dog.find(@like.dog.id)
  end

  def like_params
    params.permit(:user_id, :dog_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def can_edit?(dog)
    logged_in? &&
      current_user.owner_of?(dog)
  end

  def can_like?(dog)
    logged_in? &&
      !current_user.owner_of?(dog)
  end

  private

  def logged_in?
    current_user.present?
  end
end

app/views/dogs/_dog_carousel.html.erb
<div id="dog-carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% dog.images.each_with_index do |image, counter| %>
      <li data-target="#dog-carousel" data-slide-to="<%= counter %>" class="<%= counter == 0 ? 'active' : '' %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner" role="listbox">
    <% dog.images.each_with_index do |image, counter| %>
    <div class="<%= counter == 0 ? 'item active' : 'item' %>">
        <%= image_tag url_for(image), alt: "Photo of #{dog.name}" %>
      <div class="container">
        <div class="carousel-caption">
            <p><%= dog.description %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#dog-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#dog-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/dogs/_dog_like.html.erb
<small><%= dog.get_likes.size %></small>
<small> Likes </small>
<% if can_like %>
<span>
  <% if current_user.voted_up_on? dog %>
    <%= link_to 'Unlike', dislike_dog_path(dog), method: :put, class: 'btn btn-primary'%>
  <% else %>
    <%= link_to 'Like', like_dog_path(dog), method: :put, class: 'btn btn-primary' %>
  <% end %>
</span>
<% end %>

app/views/dogs/_dogs.html.erb
<div class="container text-center">
  <div class="text-right mb-3 text-dark text-large">
    <%= link_to "Sort By Likes", :controller => "dogs", :action => "index", :sort_params => true  %>
  </div>
  <div class="row">
    <%= render partial: 'thumbnail', collection: @dogs, as: :dog %>
 </div>
  <div id="page_links">
    <%= will_paginate @dogs, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :images, as: :file, input_html: { multiple: true } %>

  <% @dog.images.each do |image| %>
    <%= image_tag image %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_likes.html.erb
<% if can_like?(dog) %>
  <% if current_user.likes?(dog) %>
    <%= link_to "Unlike", dog_like_path(dog), method: :delete, remote: true %>
  <% else %>
    <%= link_to "Like", dog_likes_path(dog), method: :post, remote: true %>
  <% end %>
<% end %>

<p>Likes: <%= dog.likes.count %></p>

app/views/dogs/_thumbnail.html.erb
<a href="<%= url_for(dog) %>">
  <article>
    <h2 class="dog-name"><%= dog.name %></h2>
    <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
  </article>
</a>
<% if dog_counter % 2 == 1 %>
  <%= image_tag 'ad.jpg', class: "ad", alt: "A very cool ad." %>
<% end %>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<% if @sorted %>
  <%= link_to "Unsort", root_path, title: "sort by likes", id: 'sort' %>
<% else %>
  <%= link_to "Sort by Likes", root_path + '?sort=likes', title: "unsort by likes", id: 'sort' %>
<% end %>
<%= will_paginate @dogs %>
<%= render partial: 'thumbnail', collection: @dogs, as: :dog %>
<%= will_paginate @dogs %>

app/views/dogs/index.js.erb
$("#dogs").html('<%=  escape_javascript(render 'dogs') %>');
$('.pagination a').attr('data-remote', 'true');

app/views/dogs/new.html.erb
<h1 class="d-flex flex-row justify-content-sm-center align-items-center">Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<section>
  <h2>
    <%= @dog.name %>
    <% unless current_user.nil? || @dog.owner == current_user %>
      <% if current_user&.voted_for?(@dog) %>
        <%= link_to "❤️", like_dog_path(@dog), title: "click to unlike", id: 'like_dog_link' %>
      <% else %>
        <%= link_to "🤍", like_dog_path(@dog), title: "click to like", id: 'unlike_dog_link' %>
      <% end %>
    <% end %>
  </h2>

  <% @dog.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>

  <p><%= @dog.description %></p>

  <% if current_user && @dog.owner == current_user %>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="layout">
      <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
          <h1 class="navbar-text"><%= link_to 'Dog Profile Demo', root_path %></h1>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to 'Add your dog', new_dog_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </header>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>

  </body>
</html>

app/views/likes/create.js.erb
document
.getElementById("dog_<%= @dog.id %>_likes")
.innerHTML = "<%= j render partial: "dogs/likes", locals: { dog: @dog } %>";

app/views/likes/destroy.js.erb
document
.getElementById("dog_<%= @dog.id %>_likes")
.innerHTML = "<%= j render partial: "dogs/likes", locals: { dog: @dog } %>";

app/views/shared/_ad.html.erb
<%= image_tag("ad.jpg") %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Dog Profile Demo', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li>
          <%= link_to 'Add your dog', new_dog_path %>
        </li>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to 'Sign in', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>